version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch:/usr/share/elasticsearch/data'
  kibana:
    image: kibana:5
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - 'mongo:/data'
    command: mongod --rest --httpinterface

volumes:
  elasticsearch:
  mongo:
